// @ts-nocheck
export const BUILT_IN_PROVIDER_DISPLAY_NAMES: Record<string, string> = {
	anthropic: "Anthropic",
	"amazon-bedrock": "Amazon Bedrock",
	"azure-openai-responses": "Azure OpenAI Responses",
	cerebras: "Cerebras",
	"cloudflare-ai-gateway": "Cloudflare Core Gateway",
	"cloudflare-workers-ai": "Cloudflare Workers Core",
	deepseek: "DeepSeek (Google ile)",
	fireworks: "Fireworks",
	google: "Google Gemini",
	"google-vertex": "Google Vertex Core",
	groq: "Groq",
	huggingface: "Hugging Face",
	"kimi-coding": "Kimi For Coding",
	mistral: "Mistral",
	minimax: "MiniMax",
	"minimax-cn": "MiniMax (China)",
	moonshotai: "Moonshot Core",
	"moonshotai-cn": "Moonshot Core (China)",
	opencode: "OpenCode Zen",
	"opencode-go": "OpenCode Go",
	openai: "OpenAI",
	openrouter: "OpenRouter",
	"vercel-ai-gateway": "Vercel Core Gateway",
	xai: "xCore",
	"openai-codex": "Codex (Google ile)",
	zai: "ZCore",
	xiaomi: "Xiaomi MiMo",
	"xiaomi-token-plan-cn": "Xiaomi MiMo Token Plan (China)",
	"xiaomi-token-plan-ams": "Xiaomi MiMo Token Plan (Amsterdam)",
	"xiaomi-token-plan-sgp": "Xiaomi MiMo Token Plan (Singapore)",
	ollama: "Ollama",
	antigravity: "Antigravity",
};
